PotStageHistory module
tristanjahier/zoho-crm-php pull request #3
Opened 2018-05-14 11:04 UTC by Haru0

2018-05-15 14:00 UTC, tristanjahier requested changes
Nice work, I think you understood the structure of this library quite well, but I request 2 changes.

2018-05-15 14:00 UTC, tristanjahier commented on src/Api/Modules/PotStageHistory.php
> +    public function getPotentialHistory($potentialId)
Variable naming: you must replace `$potentialId` with `$potential_id`.
This naming convention could change in a future release, but at least for now we shall stick to the same thing everywhere.

2018-05-15 14:00 UTC, tristanjahier commented on src/Api/Modules/PotStageHistory.php
> +        return $this->getRelatedById('Potential', $potentialId)->fetch()->getContent();
The `->fetch()->getContent()` part must be called explicitely by the developer or is done automatically by the `Client`, therefore you must remove it.

To achieve the same thing automatically, you need to set these preferences:
1. `fetch()` is done by setting `'auto_fetch_paginated_requests'` to `true`.
2. `getContent()` is done by setting `'response_mode'` to `Zoho\CRM\ClientResponseMode::DIRECT`.

Notice the preference `'records_as_entities'`, used to transform records into entities automatically.

2018-05-15 14:05 UTC, tristanjahier requested changes

2018-05-15 14:05 UTC, tristanjahier commented on src/Api/Modules/PotStageHistory.php
> +        return $this->getRelatedById('Potential', $potentialId)->fetch()->getContent();
You are setting the `parentModule` (1st argument) of the request to `'Potential'`. But the documentation says it must be `'Potentials'` (plural), so even if it works either way, you must change it.

2018-05-16 08:03 UTC, Haru0 commented
Changes applied, please review.

2018-05-16 11:08 UTC, merged

2018-05-16 11:09 UTC, tristanjahier commented
All good! Bravo! 👏

2018-05-16 11:16 UTC, tristanjahier commented
All good! Bravo! 👏